### ISSUE TITLE
1.16.5 Compressed and Extremely Compressed Bonemeal are much weaker than their 1.12.2 counterparts

### ISSUE THREAD

**Issue by darthvader45** [blay09/Fertilization#11]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.20

### Mod Version

5.2.0

### Describe the Issue

Compressed and extremely compressed bonemeal don't work as well on Pam's crops as they used to.  Normally in 1.12.2 I'd be able to get a full inventory of crops, but now a stack of extremely compressed bonemeal barely gets me half a dozen stacks.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by BlayTheNinth** [comment]
Tested on 1.19.3 (the code hasn't really changed since 1.16 and 1.16 isn't supported anymore) and I got the expected amount of yield.

1. 64 Bonemeal: 25 Wheat, 50 Seeds
    - Bonemeal to Wheat: 64 / 25 = 2.56
    - Bonemeal to Seeds: 64 / 50 = 1.28

2. 64 Compressed Bonemeal (cost: 256 Bonemeal): 110 Wheat, 182 Seeds
    - Bonemeal to Wheat: 256 / 110 = 2.327
    - Bonemeal to Seeds: 256 / 182 = 1.407

2. 64 Extremely Compressed Bonemeal (cost: 2304 Bonemeal): 963 Wheat, 1614 Seeds
    - Bonemeal to Wheat: 2304 / 963 = 2.392
    - Bonemeal to Seeds: 2304 / 1614 = 1.427

**Comment by darthvader45** [comment]
Ah, I was talking about the crops from Pam's Harvestcraft, but that might be on their end, idk.
